name: flutter_menu_app
description: A simple Flutter app displaying a scrollable restaurant menu.

publish_to: "none"

# App version
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/f_0.png
    - images/f_1.png
    - images/f_2.png
    - images/f_3.png
    - images/f_4.png
    - images/f_5.png
    - images/f_6.png
    - images/f_7.png
    - images/f_8.png
    - images/Header-image.png
    - images/delivery.svg
    - images/clock.svg

# Optional metadata (update these after pushing to GitHub)
homepage: https://github.com/yourusername/flutter_menu_app
repository: https://github.com/yourusername/flutter_menu_app
